/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_BandParameters_v1090_H_
#define	_BandParameters_v1090_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqBandIndicator-v9e0.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BandParameters-v1090 */
typedef struct BandParameters_v1090 {
	FreqBandIndicator_v9e0_t	*bandEUTRA_v1090	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandParameters_v1090_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandParameters_v1090;

#ifdef __cplusplus
}
#endif

#endif	/* _BandParameters_v1090_H_ */
#include <asn_internal.h>
