/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-UE-Variables"
 * 	found in "36331-850.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_CellsTriggeredList_H_
#define	_CellsTriggeredList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CellsTriggeredList */
typedef struct CellsTriggeredList {
	A_SEQUENCE_OF(PhysCellId_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellsTriggeredList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellsTriggeredList;

#ifdef __cplusplus
}
#endif

#endif	/* _CellsTriggeredList_H_ */
#include <asn_internal.h>
