/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_CSI_Process_r11_H_
#define	_CSI_Process_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CSI-ProcessId-r11.h"
#include "CSI-RS-ConfigNZPId-r11.h"
#include "CSI-IM-ConfigId-r11.h"
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CSI_Process_r11__alternativeCodebookEnabledFor4TXProc_r12 {
	CSI_Process_r11__alternativeCodebookEnabledFor4TXProc_r12_true	= 0
} e_CSI_Process_r11__alternativeCodebookEnabledFor4TXProc_r12;

/* Forward declarations */
struct CQI_ReportBothProc_r11;
struct CQI_ReportAperiodicProc_r11;
struct P_C_AndCBSR_r11;

/* CSI-Process-r11 */
typedef struct CSI_Process_r11 {
	CSI_ProcessId_r11_t	 csi_ProcessId_r11;
	CSI_RS_ConfigNZPId_r11_t	 csi_RS_ConfigNZPId_r11;
	CSI_IM_ConfigId_r11_t	 csi_IM_ConfigId_r11;
	struct CSI_Process_r11__p_C_AndCBSRList_r11 {
		A_SEQUENCE_OF(struct P_C_AndCBSR_r11) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} p_C_AndCBSRList_r11;
	struct CQI_ReportBothProc_r11	*cqi_ReportBothProc_r11	/* OPTIONAL */;
	long	*cqi_ReportPeriodicProcId_r11	/* OPTIONAL */;
	struct CQI_ReportAperiodicProc_r11	*cqi_ReportAperiodicProc_r11	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	long	*alternativeCodebookEnabledFor4TXProc_r12	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CSI_Process_r11_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_alternativeCodebookEnabledFor4TXProc_r12_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CSI_Process_r11;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CQI-ReportBothProc-r11.h"
#include "CQI-ReportAperiodicProc-r11.h"
#include "P-C-AndCBSR-r11.h"

#endif	/* _CSI_Process_r11_H_ */
#include <asn_internal.h>
