/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_DMRS_Config_r11_H_
#define	_DMRS_Config_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DMRS_Config_r11_PR {
	DMRS_Config_r11_PR_NOTHING,	/* No components present */
	DMRS_Config_r11_PR_release,
	DMRS_Config_r11_PR_setup
} DMRS_Config_r11_PR;

/* DMRS-Config-r11 */
typedef struct DMRS_Config_r11 {
	DMRS_Config_r11_PR present;
	union DMRS_Config_r11_u {
		NULL_t	 release;
		struct DMRS_Config_r11__setup {
			long	 scramblingIdentity_r11;
			long	 scramblingIdentity2_r11;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} setup;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DMRS_Config_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DMRS_Config_r11;

#ifdef __cplusplus
}
#endif

#endif	/* _DMRS_Config_r11_H_ */
#include <asn_internal.h>
