/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_EPDCCH_SetConfig_r11_H_
#define	_EPDCCH_SetConfig_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EPDCCH-SetConfigId-r11.h"
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include "PDSCH-RE-MappingQCL-ConfigId-r11.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EPDCCH_SetConfig_r11__transmissionType_r11 {
	EPDCCH_SetConfig_r11__transmissionType_r11_localised	= 0,
	EPDCCH_SetConfig_r11__transmissionType_r11_distributed	= 1
} e_EPDCCH_SetConfig_r11__transmissionType_r11;
typedef enum EPDCCH_SetConfig_r11__resourceBlockAssignment_r11__numberPRB_Pairs_r11 {
	EPDCCH_SetConfig_r11__resourceBlockAssignment_r11__numberPRB_Pairs_r11_n2	= 0,
	EPDCCH_SetConfig_r11__resourceBlockAssignment_r11__numberPRB_Pairs_r11_n4	= 1,
	EPDCCH_SetConfig_r11__resourceBlockAssignment_r11__numberPRB_Pairs_r11_n8	= 2
} e_EPDCCH_SetConfig_r11__resourceBlockAssignment_r11__numberPRB_Pairs_r11;

/* EPDCCH-SetConfig-r11 */
typedef struct EPDCCH_SetConfig_r11 {
	EPDCCH_SetConfigId_r11_t	 setConfigId_r11;
	long	 transmissionType_r11;
	struct EPDCCH_SetConfig_r11__resourceBlockAssignment_r11 {
		long	 numberPRB_Pairs_r11;
		BIT_STRING_t	 resourceBlockAssignment_r11;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} resourceBlockAssignment_r11;
	long	 dmrs_ScramblingSequenceInt_r11;
	long	 pucch_ResourceStartOffset_r11;
	PDSCH_RE_MappingQCL_ConfigId_r11_t	*re_MappingQCL_ConfigId_r11	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EPDCCH_SetConfig_r11_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_transmissionType_r11_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_numberPRB_Pairs_r11_7;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_EPDCCH_SetConfig_r11;

#ifdef __cplusplus
}
#endif

#endif	/* _EPDCCH_SetConfig_r11_H_ */
#include <asn_internal.h>
