/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-InterNodeDefinitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_HandoverPreparationInformation_H_
#define	_HandoverPreparationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "HandoverPreparationInformation-r8-IEs.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HandoverPreparationInformation__criticalExtensions_PR {
	HandoverPreparationInformation__criticalExtensions_PR_NOTHING,	/* No components present */
	HandoverPreparationInformation__criticalExtensions_PR_c1,
	HandoverPreparationInformation__criticalExtensions_PR_criticalExtensionsFuture
} HandoverPreparationInformation__criticalExtensions_PR;
typedef enum HandoverPreparationInformation__criticalExtensions__c1_PR {
	HandoverPreparationInformation__criticalExtensions__c1_PR_NOTHING,	/* No components present */
	HandoverPreparationInformation__criticalExtensions__c1_PR_handoverPreparationInformation_r8,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare7,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare6,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare5,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare4,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare3,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare2,
	HandoverPreparationInformation__criticalExtensions__c1_PR_spare1
} HandoverPreparationInformation__criticalExtensions__c1_PR;

/* HandoverPreparationInformation */
typedef struct HandoverPreparationInformation {
	struct HandoverPreparationInformation__criticalExtensions {
		HandoverPreparationInformation__criticalExtensions_PR present;
		union HandoverPreparationInformation__criticalExtensions_u {
			struct HandoverPreparationInformation__criticalExtensions__c1 {
				HandoverPreparationInformation__criticalExtensions__c1_PR present;
				union HandoverPreparationInformation__criticalExtensions__c1_u {
					HandoverPreparationInformation_r8_IEs_t	 handoverPreparationInformation_r8;
					NULL_t	 spare7;
					NULL_t	 spare6;
					NULL_t	 spare5;
					NULL_t	 spare4;
					NULL_t	 spare3;
					NULL_t	 spare2;
					NULL_t	 spare1;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} c1;
			struct HandoverPreparationInformation__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandoverPreparationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandoverPreparationInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _HandoverPreparationInformation_H_ */
#include <asn_internal.h>
