/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "MBMS-SAI-InterFreq-r11.h"

static asn_TYPE_member_t asn_MBR_MBMS_SAI_InterFreq_r11_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MBMS_SAI_InterFreq_r11, dl_CarrierFreq_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"dl-CarrierFreq-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MBMS_SAI_InterFreq_r11, mbms_SAI_List_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS_SAI_List_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"mbms-SAI-List-r11"
		},
};
static ber_tlv_tag_t asn_DEF_MBMS_SAI_InterFreq_r11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MBMS_SAI_InterFreq_r11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl-CarrierFreq-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* mbms-SAI-List-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_MBMS_SAI_InterFreq_r11_specs_1 = {
	sizeof(struct MBMS_SAI_InterFreq_r11),
	offsetof(struct MBMS_SAI_InterFreq_r11, _asn_ctx),
	asn_MAP_MBMS_SAI_InterFreq_r11_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MBMS_SAI_InterFreq_r11 = {
	"MBMS-SAI-InterFreq-r11",
	"MBMS-SAI-InterFreq-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MBMS_SAI_InterFreq_r11_tags_1,
	sizeof(asn_DEF_MBMS_SAI_InterFreq_r11_tags_1)
		/sizeof(asn_DEF_MBMS_SAI_InterFreq_r11_tags_1[0]), /* 1 */
	asn_DEF_MBMS_SAI_InterFreq_r11_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMS_SAI_InterFreq_r11_tags_1)
		/sizeof(asn_DEF_MBMS_SAI_InterFreq_r11_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MBMS_SAI_InterFreq_r11_1,
	2,	/* Elements count */
	&asn_SPC_MBMS_SAI_InterFreq_r11_specs_1	/* Additional specs */
};

