/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_MBMS_SAI_InterFreq_r11_H_
#define	_MBMS_SAI_InterFreq_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueEUTRA-r9.h"
#include "MBMS-SAI-List-r11.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MBMS-SAI-InterFreq-r11 */
typedef struct MBMS_SAI_InterFreq_r11 {
	ARFCN_ValueEUTRA_r9_t	 dl_CarrierFreq_r11;
	MBMS_SAI_List_r11_t	 mbms_SAI_List_r11;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMS_SAI_InterFreq_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMS_SAI_InterFreq_r11;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMS_SAI_InterFreq_r11_H_ */
#include <asn_internal.h>
