/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_MBSFN_AreaInfoList_r9_H_
#define	_MBSFN_AreaInfoList_r9_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MBSFN_AreaInfo_r9;

/* MBSFN-AreaInfoList-r9 */
typedef struct MBSFN_AreaInfoList_r9 {
	A_SEQUENCE_OF(struct MBSFN_AreaInfo_r9) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBSFN_AreaInfoList_r9_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBSFN_AreaInfoList_r9;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MBSFN-AreaInfo-r9.h"

#endif	/* _MBSFN_AreaInfoList_r9_H_ */
#include <asn_internal.h>
