/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "MeasResultEUTRA.h"

static int
primaryPLMN_Suitable_r12_12_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
primaryPLMN_Suitable_r12_12_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
primaryPLMN_Suitable_r12_12_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
primaryPLMN_Suitable_r12_12_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
primaryPLMN_Suitable_r12_12_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
primaryPLMN_Suitable_r12_12_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
primaryPLMN_Suitable_r12_12_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
primaryPLMN_Suitable_r12_12_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
primaryPLMN_Suitable_r12_12_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	primaryPLMN_Suitable_r12_12_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_primaryPLMN_Suitable_r12_constr_12 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_cgi_Info_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, cellGlobalId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellGlobalId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, trackingAreaCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrackingAreaCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"trackingAreaCode"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__cgi_Info, plmn_IdentityList),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMN_IdentityList2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"plmn-IdentityList"
		},
};
static int asn_MAP_cgi_Info_oms_3[] = { 2 };
static ber_tlv_tag_t asn_DEF_cgi_Info_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_cgi_Info_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGlobalId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* trackingAreaCode */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* plmn-IdentityList */
};
static asn_SEQUENCE_specifics_t asn_SPC_cgi_Info_specs_3 = {
	sizeof(struct MeasResultEUTRA__cgi_Info),
	offsetof(struct MeasResultEUTRA__cgi_Info, _asn_ctx),
	asn_MAP_cgi_Info_tag2el_3,
	3,	/* Count of tags in the map */
	asn_MAP_cgi_Info_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cgi_Info_3 = {
	"cgi-Info",
	"cgi-Info",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_cgi_Info_tags_3,
	sizeof(asn_DEF_cgi_Info_tags_3)
		/sizeof(asn_DEF_cgi_Info_tags_3[0]) - 1, /* 1 */
	asn_DEF_cgi_Info_tags_3,	/* Same as above */
	sizeof(asn_DEF_cgi_Info_tags_3)
		/sizeof(asn_DEF_cgi_Info_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_cgi_Info_3,
	3,	/* Elements count */
	&asn_SPC_cgi_Info_specs_3	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_primaryPLMN_Suitable_r12_value2enum_12[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_primaryPLMN_Suitable_r12_enum2value_12[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_primaryPLMN_Suitable_r12_specs_12 = {
	asn_MAP_primaryPLMN_Suitable_r12_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_primaryPLMN_Suitable_r12_enum2value_12,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_primaryPLMN_Suitable_r12_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_primaryPLMN_Suitable_r12_12 = {
	"primaryPLMN-Suitable-r12",
	"primaryPLMN-Suitable-r12",
	primaryPLMN_Suitable_r12_12_free,
	primaryPLMN_Suitable_r12_12_print,
	primaryPLMN_Suitable_r12_12_constraint,
	primaryPLMN_Suitable_r12_12_decode_ber,
	primaryPLMN_Suitable_r12_12_encode_der,
	primaryPLMN_Suitable_r12_12_decode_xer,
	primaryPLMN_Suitable_r12_12_encode_xer,
	primaryPLMN_Suitable_r12_12_decode_uper,
	primaryPLMN_Suitable_r12_12_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_primaryPLMN_Suitable_r12_tags_12,
	sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12)
		/sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12[0]) - 1, /* 1 */
	asn_DEF_primaryPLMN_Suitable_r12_tags_12,	/* Same as above */
	sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12)
		/sizeof(asn_DEF_primaryPLMN_Suitable_r12_tags_12[0]), /* 2 */
	&asn_PER_type_primaryPLMN_Suitable_r12_constr_12,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_primaryPLMN_Suitable_r12_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResult_7[] = {
	{ ATF_POINTER, 4, offsetof(struct MeasResultEUTRA__measResult, rsrpResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rsrpResult"
		},
	{ ATF_POINTER, 3, offsetof(struct MeasResultEUTRA__measResult, rsrqResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rsrqResult"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasResultEUTRA__measResult, additionalSI_Info_r9),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AdditionalSI_Info_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"additionalSI-Info-r9"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__measResult, primaryPLMN_Suitable_r12),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_primaryPLMN_Suitable_r12_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"primaryPLMN-Suitable-r12"
		},
};
static int asn_MAP_measResult_oms_7[] = { 0, 1, 2, 3 };
static ber_tlv_tag_t asn_DEF_measResult_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_measResult_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rsrqResult */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* additionalSI-Info-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* primaryPLMN-Suitable-r12 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResult_specs_7 = {
	sizeof(struct MeasResultEUTRA__measResult),
	offsetof(struct MeasResultEUTRA__measResult, _asn_ctx),
	asn_MAP_measResult_tag2el_7,
	4,	/* Count of tags in the map */
	asn_MAP_measResult_oms_7,	/* Optional members */
	2, 2,	/* Root/Additions */
	1,	/* Start extensions */
	5	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResult_7 = {
	"measResult",
	"measResult",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_measResult_tags_7,
	sizeof(asn_DEF_measResult_tags_7)
		/sizeof(asn_DEF_measResult_tags_7[0]) - 1, /* 1 */
	asn_DEF_measResult_tags_7,	/* Same as above */
	sizeof(asn_DEF_measResult_tags_7)
		/sizeof(asn_DEF_measResult_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_measResult_7,
	4,	/* Elements count */
	&asn_SPC_measResult_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_MeasResultEUTRA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, physCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"physCellId"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA, cgi_Info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_cgi_Info_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cgi-Info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, measResult),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_measResult_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResult"
		},
};
static int asn_MAP_MeasResultEUTRA_oms_1[] = { 1 };
static ber_tlv_tag_t asn_DEF_MeasResultEUTRA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MeasResultEUTRA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cgi-Info */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* measResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_MeasResultEUTRA_specs_1 = {
	sizeof(struct MeasResultEUTRA),
	offsetof(struct MeasResultEUTRA, _asn_ctx),
	asn_MAP_MeasResultEUTRA_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MeasResultEUTRA_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_MeasResultEUTRA = {
	"MeasResultEUTRA",
	"MeasResultEUTRA",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MeasResultEUTRA_tags_1,
	sizeof(asn_DEF_MeasResultEUTRA_tags_1)
		/sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
	asn_DEF_MeasResultEUTRA_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasResultEUTRA_tags_1)
		/sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MeasResultEUTRA_1,
	3,	/* Elements count */
	&asn_SPC_MeasResultEUTRA_specs_1	/* Additional specs */
};

