/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-850.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_MeasParameters_H_
#define	_MeasParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BandListEUTRA.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasParameters */
typedef struct MeasParameters {
	BandListEUTRA_t	 bandListEUTRA;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasParameters_H_ */
#include <asn_internal.h>
