/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-850.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_Paging_H_
#define	_Paging_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Paging__systemInfoModification {
	Paging__systemInfoModification_true	= 0
} e_Paging__systemInfoModification;
typedef enum Paging__etws_Indication {
	Paging__etws_Indication_true	= 0
} e_Paging__etws_Indication;

/* Forward declarations */
struct PagingRecordList;

/* Paging */
typedef struct Paging {
	struct PagingRecordList	*pagingRecordList	/* OPTIONAL */;
	long	*systemInfoModification	/* OPTIONAL */;
	long	*etws_Indication	/* OPTIONAL */;
	struct Paging__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Paging_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_systemInfoModification_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_etws_Indication_5;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Paging;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PagingRecordList.h"

#endif	/* _Paging_H_ */
#include <asn_internal.h>
