/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "ParametersCDMA2000-r11.h"

static int
csfb_DualRxTxSupport_r11_16_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
csfb_DualRxTxSupport_r11_16_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
csfb_DualRxTxSupport_r11_16_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
csfb_DualRxTxSupport_r11_16_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
csfb_DualRxTxSupport_r11_16_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
csfb_DualRxTxSupport_r11_16_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
csfb_DualRxTxSupport_r11_16_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
csfb_DualRxTxSupport_r11_16_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
csfb_DualRxTxSupport_r11_16_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	csfb_DualRxTxSupport_r11_16_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_longCodeState1XRTT_r11_constraint_9(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 42)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_searchWindowSize_r11_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_systemTimeInfo_r11_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_csfb_DualRxTxSupport_r11_constr_16 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_longCodeState1XRTT_r11_constr_12 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  42,  42 }	/* (SIZE(42..42)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_searchWindowSize_r11_constr_5 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_systemTimeInfo_r11_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ParametersCDMA2000_r11__systemTimeInfo_r11, choice.explicitValue),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SystemTimeInfoCDMA2000,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"explicitValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ParametersCDMA2000_r11__systemTimeInfo_r11, choice.defaultValue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"defaultValue"
		},
};
static asn_TYPE_tag2member_t asn_MAP_systemTimeInfo_r11_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* explicitValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* defaultValue */
};
static asn_CHOICE_specifics_t asn_SPC_systemTimeInfo_r11_specs_2 = {
	sizeof(struct ParametersCDMA2000_r11__systemTimeInfo_r11),
	offsetof(struct ParametersCDMA2000_r11__systemTimeInfo_r11, _asn_ctx),
	offsetof(struct ParametersCDMA2000_r11__systemTimeInfo_r11, present),
	sizeof(((struct ParametersCDMA2000_r11__systemTimeInfo_r11 *)0)->present),
	asn_MAP_systemTimeInfo_r11_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_systemTimeInfo_r11_2 = {
	"systemTimeInfo-r11",
	"systemTimeInfo-r11",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_systemTimeInfo_r11_constr_2,
	asn_MBR_systemTimeInfo_r11_2,
	2,	/* Elements count */
	&asn_SPC_systemTimeInfo_r11_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_parametersHRPD_r11_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ParametersCDMA2000_r11__parametersHRPD_r11, preRegistrationInfoHRPD_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PreRegistrationInfoHRPD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"preRegistrationInfoHRPD-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct ParametersCDMA2000_r11__parametersHRPD_r11, cellReselectionParametersHRPD_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellReselectionParametersCDMA2000_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellReselectionParametersHRPD-r11"
		},
};
static int asn_MAP_parametersHRPD_r11_oms_6[] = { 1 };
static ber_tlv_tag_t asn_DEF_parametersHRPD_r11_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_parametersHRPD_r11_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* preRegistrationInfoHRPD-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cellReselectionParametersHRPD-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_parametersHRPD_r11_specs_6 = {
	sizeof(struct ParametersCDMA2000_r11__parametersHRPD_r11),
	offsetof(struct ParametersCDMA2000_r11__parametersHRPD_r11, _asn_ctx),
	asn_MAP_parametersHRPD_r11_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_parametersHRPD_r11_oms_6,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_parametersHRPD_r11_6 = {
	"parametersHRPD-r11",
	"parametersHRPD-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_parametersHRPD_r11_tags_6,
	sizeof(asn_DEF_parametersHRPD_r11_tags_6)
		/sizeof(asn_DEF_parametersHRPD_r11_tags_6[0]) - 1, /* 1 */
	asn_DEF_parametersHRPD_r11_tags_6,	/* Same as above */
	sizeof(asn_DEF_parametersHRPD_r11_tags_6)
		/sizeof(asn_DEF_parametersHRPD_r11_tags_6[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_parametersHRPD_r11_6,
	2,	/* Elements count */
	&asn_SPC_parametersHRPD_r11_specs_6	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_csfb_DualRxTxSupport_r11_value2enum_16[] = {
	{ 0,	4,	"true" }
};
static unsigned int asn_MAP_csfb_DualRxTxSupport_r11_enum2value_16[] = {
	0	/* true(0) */
};
static asn_INTEGER_specifics_t asn_SPC_csfb_DualRxTxSupport_r11_specs_16 = {
	asn_MAP_csfb_DualRxTxSupport_r11_value2enum_16,	/* "tag" => N; sorted by tag */
	asn_MAP_csfb_DualRxTxSupport_r11_enum2value_16,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_csfb_DualRxTxSupport_r11_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_csfb_DualRxTxSupport_r11_16 = {
	"csfb-DualRxTxSupport-r11",
	"csfb-DualRxTxSupport-r11",
	csfb_DualRxTxSupport_r11_16_free,
	csfb_DualRxTxSupport_r11_16_print,
	csfb_DualRxTxSupport_r11_16_constraint,
	csfb_DualRxTxSupport_r11_16_decode_ber,
	csfb_DualRxTxSupport_r11_16_encode_der,
	csfb_DualRxTxSupport_r11_16_decode_xer,
	csfb_DualRxTxSupport_r11_16_encode_xer,
	csfb_DualRxTxSupport_r11_16_decode_uper,
	csfb_DualRxTxSupport_r11_16_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_csfb_DualRxTxSupport_r11_tags_16,
	sizeof(asn_DEF_csfb_DualRxTxSupport_r11_tags_16)
		/sizeof(asn_DEF_csfb_DualRxTxSupport_r11_tags_16[0]) - 1, /* 1 */
	asn_DEF_csfb_DualRxTxSupport_r11_tags_16,	/* Same as above */
	sizeof(asn_DEF_csfb_DualRxTxSupport_r11_tags_16)
		/sizeof(asn_DEF_csfb_DualRxTxSupport_r11_tags_16[0]), /* 2 */
	&asn_PER_type_csfb_DualRxTxSupport_r11_constr_16,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_csfb_DualRxTxSupport_r11_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_parameters1XRTT_r11_9[] = {
	{ ATF_POINTER, 7, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, csfb_RegistrationParam1XRTT_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSFB_RegistrationParam1XRTT,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csfb-RegistrationParam1XRTT-r11"
		},
	{ ATF_POINTER, 6, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, csfb_RegistrationParam1XRTT_Ext_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CSFB_RegistrationParam1XRTT_v920,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csfb-RegistrationParam1XRTT-Ext-r11"
		},
	{ ATF_POINTER, 5, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, longCodeState1XRTT_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		memb_longCodeState1XRTT_r11_constraint_9,
		&asn_PER_memb_longCodeState1XRTT_r11_constr_12,
		0,
		"longCodeState1XRTT-r11"
		},
	{ ATF_POINTER, 4, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, cellReselectionParameters1XRTT_r11),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellReselectionParametersCDMA2000_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellReselectionParameters1XRTT-r11"
		},
	{ ATF_POINTER, 3, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, ac_BarringConfig1XRTT_r11),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AC_BarringConfig1XRTT_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"ac-BarringConfig1XRTT-r11"
		},
	{ ATF_POINTER, 2, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, csfb_SupportForDualRxUEs_r11),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csfb-SupportForDualRxUEs-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, csfb_DualRxTxSupport_r11),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_csfb_DualRxTxSupport_r11_16,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"csfb-DualRxTxSupport-r11"
		},
};
static int asn_MAP_parameters1XRTT_r11_oms_9[] = { 0, 1, 2, 3, 4, 5, 6 };
static ber_tlv_tag_t asn_DEF_parameters1XRTT_r11_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_parameters1XRTT_r11_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* csfb-RegistrationParam1XRTT-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* csfb-RegistrationParam1XRTT-Ext-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* longCodeState1XRTT-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cellReselectionParameters1XRTT-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ac-BarringConfig1XRTT-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* csfb-SupportForDualRxUEs-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* csfb-DualRxTxSupport-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_parameters1XRTT_r11_specs_9 = {
	sizeof(struct ParametersCDMA2000_r11__parameters1XRTT_r11),
	offsetof(struct ParametersCDMA2000_r11__parameters1XRTT_r11, _asn_ctx),
	asn_MAP_parameters1XRTT_r11_tag2el_9,
	7,	/* Count of tags in the map */
	asn_MAP_parameters1XRTT_r11_oms_9,	/* Optional members */
	7, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_parameters1XRTT_r11_9 = {
	"parameters1XRTT-r11",
	"parameters1XRTT-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_parameters1XRTT_r11_tags_9,
	sizeof(asn_DEF_parameters1XRTT_r11_tags_9)
		/sizeof(asn_DEF_parameters1XRTT_r11_tags_9[0]) - 1, /* 1 */
	asn_DEF_parameters1XRTT_r11_tags_9,	/* Same as above */
	sizeof(asn_DEF_parameters1XRTT_r11_tags_9)
		/sizeof(asn_DEF_parameters1XRTT_r11_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_parameters1XRTT_r11_9,
	7,	/* Elements count */
	&asn_SPC_parameters1XRTT_r11_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ParametersCDMA2000_r11_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ParametersCDMA2000_r11, systemTimeInfo_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_systemTimeInfo_r11_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"systemTimeInfo-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ParametersCDMA2000_r11, searchWindowSize_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_searchWindowSize_r11_constraint_1,
		&asn_PER_memb_searchWindowSize_r11_constr_5,
		0,
		"searchWindowSize-r11"
		},
	{ ATF_POINTER, 2, offsetof(struct ParametersCDMA2000_r11, parametersHRPD_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_parametersHRPD_r11_6,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"parametersHRPD-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct ParametersCDMA2000_r11, parameters1XRTT_r11),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_parameters1XRTT_r11_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"parameters1XRTT-r11"
		},
};
static int asn_MAP_ParametersCDMA2000_r11_oms_1[] = { 0, 2, 3 };
static ber_tlv_tag_t asn_DEF_ParametersCDMA2000_r11_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ParametersCDMA2000_r11_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* systemTimeInfo-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* searchWindowSize-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* parametersHRPD-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* parameters1XRTT-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_ParametersCDMA2000_r11_specs_1 = {
	sizeof(struct ParametersCDMA2000_r11),
	offsetof(struct ParametersCDMA2000_r11, _asn_ctx),
	asn_MAP_ParametersCDMA2000_r11_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_ParametersCDMA2000_r11_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* Start extensions */
	5	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ParametersCDMA2000_r11 = {
	"ParametersCDMA2000-r11",
	"ParametersCDMA2000-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ParametersCDMA2000_r11_tags_1,
	sizeof(asn_DEF_ParametersCDMA2000_r11_tags_1)
		/sizeof(asn_DEF_ParametersCDMA2000_r11_tags_1[0]), /* 1 */
	asn_DEF_ParametersCDMA2000_r11_tags_1,	/* Same as above */
	sizeof(asn_DEF_ParametersCDMA2000_r11_tags_1)
		/sizeof(asn_DEF_ParametersCDMA2000_r11_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ParametersCDMA2000_r11_1,
	4,	/* Elements count */
	&asn_SPC_ParametersCDMA2000_r11_specs_1	/* Additional specs */
};

