/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_BCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_BCCH_DL_SCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_MCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_PCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_DL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_CCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_UL_DCCH_Message;
extern struct asn_TYPE_descriptor_s asn_DEF_RRCConnectionRelease_v9e0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType1_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UEInformationResponse_v9e0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType2_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType5_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_SystemInformationBlockType6_v8h0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_EUTRA_Capability;
extern struct asn_TYPE_descriptor_s asn_DEF_UE_EUTRA_Capability_v9a0_IEs;
extern struct asn_TYPE_descriptor_s asn_DEF_VarConnEstFailReport_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasConfig_r10;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasConfig_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasReport_r10;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLogMeasReport_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasConfig;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMeasReportList;
extern struct asn_TYPE_descriptor_s asn_DEF_VarMobilityHistoryReport_r12;
extern struct asn_TYPE_descriptor_s asn_DEF_VarRLF_Report_r10;
extern struct asn_TYPE_descriptor_s asn_DEF_VarRLF_Report_r11;
extern struct asn_TYPE_descriptor_s asn_DEF_VarShortMAC_Input;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverCommand;
extern struct asn_TYPE_descriptor_s asn_DEF_HandoverPreparationInformation;
extern struct asn_TYPE_descriptor_s asn_DEF_UERadioAccessCapabilityInformation;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module EUTRA-RRC-Definitions in 36331-c10.asn */
	&asn_DEF_BCCH_BCH_Message,	
	&asn_DEF_BCCH_DL_SCH_Message,	
	&asn_DEF_MCCH_Message,	
	&asn_DEF_PCCH_Message,	
	&asn_DEF_DL_CCCH_Message,	
	&asn_DEF_DL_DCCH_Message,	
	&asn_DEF_UL_CCCH_Message,	
	&asn_DEF_UL_DCCH_Message,	
	&asn_DEF_RRCConnectionRelease_v9e0_IEs,	
	&asn_DEF_SystemInformationBlockType1_v8h0_IEs,	
	&asn_DEF_UEInformationResponse_v9e0_IEs,	
	&asn_DEF_SystemInformationBlockType2_v8h0_IEs,	
	&asn_DEF_SystemInformationBlockType5_v8h0_IEs,	
	&asn_DEF_SystemInformationBlockType6_v8h0_IEs,	
	&asn_DEF_UE_EUTRA_Capability,	
	&asn_DEF_UE_EUTRA_Capability_v9a0_IEs,	
	/* From module EUTRA-UE-Variables in 36331-c10.asn */
	&asn_DEF_VarConnEstFailReport_r11,	
	&asn_DEF_VarLogMeasConfig_r10,	
	&asn_DEF_VarLogMeasConfig_r11,	
	&asn_DEF_VarLogMeasReport_r10,	
	&asn_DEF_VarLogMeasReport_r11,	
	&asn_DEF_VarMeasConfig,	
	&asn_DEF_VarMeasReportList,	
	&asn_DEF_VarMobilityHistoryReport_r12,	
	&asn_DEF_VarRLF_Report_r10,	
	&asn_DEF_VarRLF_Report_r11,	
	&asn_DEF_VarShortMAC_Input,	
	/* From module EUTRA-InterNodeDefinitions in 36331-c10.asn */
	&asn_DEF_HandoverCommand,	
	&asn_DEF_HandoverPreparationInformation,	
	&asn_DEF_UERadioAccessCapabilityInformation,	
	0
};

