/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-850.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_PhysicalConfigDedicated_H_
#define	_PhysicalConfigDedicated_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AntennaInfoDedicated.h"
#include <NULL.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PhysicalConfigDedicated__antennaInfo_PR {
	PhysicalConfigDedicated__antennaInfo_PR_NOTHING,	/* No components present */
	PhysicalConfigDedicated__antennaInfo_PR_explicitValue,
	PhysicalConfigDedicated__antennaInfo_PR_defaultValue
} PhysicalConfigDedicated__antennaInfo_PR;

/* Forward declarations */
struct PDSCH_ConfigDedicated;
struct PUCCH_ConfigDedicated;
struct PUSCH_ConfigDedicated;
struct UplinkPowerControlDedicated;
struct TPC_PDCCH_Config;
struct CQI_ReportConfig;
struct SoundingRS_UL_ConfigDedicated;
struct SchedulingRequestConfig;

/* PhysicalConfigDedicated */
typedef struct PhysicalConfigDedicated {
	struct PDSCH_ConfigDedicated	*pdsch_ConfigDedicated	/* OPTIONAL */;
	struct PUCCH_ConfigDedicated	*pucch_ConfigDedicated	/* OPTIONAL */;
	struct PUSCH_ConfigDedicated	*pusch_ConfigDedicated	/* OPTIONAL */;
	struct UplinkPowerControlDedicated	*uplinkPowerControlDedicated	/* OPTIONAL */;
	struct TPC_PDCCH_Config	*tpc_PDCCH_ConfigPUCCH	/* OPTIONAL */;
	struct TPC_PDCCH_Config	*tpc_PDCCH_ConfigPUSCH	/* OPTIONAL */;
	struct CQI_ReportConfig	*cqi_ReportConfig	/* OPTIONAL */;
	struct SoundingRS_UL_ConfigDedicated	*soundingRS_UL_ConfigDedicated	/* OPTIONAL */;
	struct PhysicalConfigDedicated__antennaInfo {
		PhysicalConfigDedicated__antennaInfo_PR present;
		union PhysicalConfigDedicated__antennaInfo_u {
			AntennaInfoDedicated_t	 explicitValue;
			NULL_t	 defaultValue;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *antennaInfo;
	struct SchedulingRequestConfig	*schedulingRequestConfig	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhysicalConfigDedicated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhysicalConfigDedicated;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDSCH-ConfigDedicated.h"
#include "PUCCH-ConfigDedicated.h"
#include "PUSCH-ConfigDedicated.h"
#include "UplinkPowerControlDedicated.h"
#include "TPC-PDCCH-Config.h"
#include "CQI-ReportConfig.h"
#include "SoundingRS-UL-ConfigDedicated.h"
#include "SchedulingRequestConfig.h"

#endif	/* _PhysicalConfigDedicated_H_ */
#include <asn_internal.h>
