/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_RE_MappingQCLConfigToAddModList_r11_H_
#define	_RE_MappingQCLConfigToAddModList_r11_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDSCH_RE_MappingQCL_Config_r11;

/* RE-MappingQCLConfigToAddModList-r11 */
typedef struct RE_MappingQCLConfigToAddModList_r11 {
	A_SEQUENCE_OF(struct PDSCH_RE_MappingQCL_Config_r11) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RE_MappingQCLConfigToAddModList_r11_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RE_MappingQCLConfigToAddModList_r11;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDSCH-RE-MappingQCL-Config-r11.h"

#endif	/* _RE_MappingQCLConfigToAddModList_r11_H_ */
#include <asn_internal.h>
