/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-850.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "ReportConfigEUTRA.h"

static int
memb_a3_Offset_constraint_9(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -30 && value <= 30)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
purpose_21_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
purpose_21_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
purpose_21_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	purpose_21_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
purpose_21_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
purpose_21_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
purpose_21_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
purpose_21_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
purpose_21_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
purpose_21_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
purpose_21_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	purpose_21_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
triggerQuantity_24_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
triggerQuantity_24_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
triggerQuantity_24_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
triggerQuantity_24_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
triggerQuantity_24_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
triggerQuantity_24_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
triggerQuantity_24_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
triggerQuantity_24_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
triggerQuantity_24_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
triggerQuantity_24_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	triggerQuantity_24_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
reportQuantity_27_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
reportQuantity_27_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
reportQuantity_27_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
reportQuantity_27_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
reportQuantity_27_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
reportQuantity_27_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
reportQuantity_27_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
reportQuantity_27_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
reportQuantity_27_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
reportQuantity_27_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	reportQuantity_27_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
reportAmount_32_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
reportAmount_32_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
reportAmount_32_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
reportAmount_32_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
reportAmount_32_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
reportAmount_32_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
reportAmount_32_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
reportAmount_32_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
reportAmount_32_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
reportAmount_32_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	reportAmount_32_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_maxReportCells_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 8)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_a3_Offset_constr_10 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6, -30,  30 }	/* (-30..30) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_eventId_constr_4 GCC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_purpose_constr_21 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_triggerType_constr_2 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_triggerQuantity_constr_24 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_reportQuantity_constr_27 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_reportAmount_constr_32 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  0,  7 }	/* (0..7) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_maxReportCells_constr_30 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (1..8) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_eventA1_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA1, a1_Threshold),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"a1-Threshold"
		},
};
static ber_tlv_tag_t asn_DEF_eventA1_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_eventA1_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* a1-Threshold */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventA1_specs_5 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA1),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA1, _asn_ctx),
	asn_MAP_eventA1_tag2el_5,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventA1_5 = {
	"eventA1",
	"eventA1",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventA1_tags_5,
	sizeof(asn_DEF_eventA1_tags_5)
		/sizeof(asn_DEF_eventA1_tags_5[0]) - 1, /* 1 */
	asn_DEF_eventA1_tags_5,	/* Same as above */
	sizeof(asn_DEF_eventA1_tags_5)
		/sizeof(asn_DEF_eventA1_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventA1_5,
	1,	/* Elements count */
	&asn_SPC_eventA1_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventA2_7[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA2, a2_Threshold),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"a2-Threshold"
		},
};
static ber_tlv_tag_t asn_DEF_eventA2_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_eventA2_tag2el_7[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* a2-Threshold */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventA2_specs_7 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA2),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA2, _asn_ctx),
	asn_MAP_eventA2_tag2el_7,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventA2_7 = {
	"eventA2",
	"eventA2",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventA2_tags_7,
	sizeof(asn_DEF_eventA2_tags_7)
		/sizeof(asn_DEF_eventA2_tags_7[0]) - 1, /* 1 */
	asn_DEF_eventA2_tags_7,	/* Same as above */
	sizeof(asn_DEF_eventA2_tags_7)
		/sizeof(asn_DEF_eventA2_tags_7[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventA2_7,
	1,	/* Elements count */
	&asn_SPC_eventA2_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventA3_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA3, a3_Offset),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_a3_Offset_constraint_9,
		&asn_PER_memb_a3_Offset_constr_10,
		0,
		"a3-Offset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA3, reportOnLeave),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportOnLeave"
		},
};
static ber_tlv_tag_t asn_DEF_eventA3_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_eventA3_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a3-Offset */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reportOnLeave */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventA3_specs_9 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA3),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA3, _asn_ctx),
	asn_MAP_eventA3_tag2el_9,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventA3_9 = {
	"eventA3",
	"eventA3",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventA3_tags_9,
	sizeof(asn_DEF_eventA3_tags_9)
		/sizeof(asn_DEF_eventA3_tags_9[0]) - 1, /* 1 */
	asn_DEF_eventA3_tags_9,	/* Same as above */
	sizeof(asn_DEF_eventA3_tags_9)
		/sizeof(asn_DEF_eventA3_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventA3_9,
	2,	/* Elements count */
	&asn_SPC_eventA3_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventA4_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA4, a4_Threshold),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"a4-Threshold"
		},
};
static ber_tlv_tag_t asn_DEF_eventA4_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_eventA4_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* a4-Threshold */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventA4_specs_12 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA4),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA4, _asn_ctx),
	asn_MAP_eventA4_tag2el_12,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventA4_12 = {
	"eventA4",
	"eventA4",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventA4_tags_12,
	sizeof(asn_DEF_eventA4_tags_12)
		/sizeof(asn_DEF_eventA4_tags_12[0]) - 1, /* 1 */
	asn_DEF_eventA4_tags_12,	/* Same as above */
	sizeof(asn_DEF_eventA4_tags_12)
		/sizeof(asn_DEF_eventA4_tags_12[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventA4_12,
	1,	/* Elements count */
	&asn_SPC_eventA4_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventA5_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA5, a5_Threshold1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"a5-Threshold1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA5, a5_Threshold2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"a5-Threshold2"
		},
};
static ber_tlv_tag_t asn_DEF_eventA5_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_eventA5_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* a5-Threshold1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* a5-Threshold2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_eventA5_specs_14 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA5),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId__eventA5, _asn_ctx),
	asn_MAP_eventA5_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventA5_14 = {
	"eventA5",
	"eventA5",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_eventA5_tags_14,
	sizeof(asn_DEF_eventA5_tags_14)
		/sizeof(asn_DEF_eventA5_tags_14[0]) - 1, /* 1 */
	asn_DEF_eventA5_tags_14,	/* Same as above */
	sizeof(asn_DEF_eventA5_tags_14)
		/sizeof(asn_DEF_eventA5_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_eventA5_14,
	2,	/* Elements count */
	&asn_SPC_eventA5_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_eventId_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, choice.eventA1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_eventA1_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventA1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, choice.eventA2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_eventA2_7,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventA2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, choice.eventA3),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_eventA3_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventA3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, choice.eventA4),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_eventA4_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventA4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, choice.eventA5),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_eventA5_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventA5"
		},
};
static asn_TYPE_tag2member_t asn_MAP_eventId_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventA1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* eventA2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* eventA3 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* eventA4 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* eventA5 */
};
static asn_CHOICE_specifics_t asn_SPC_eventId_specs_4 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event__eventId),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, _asn_ctx),
	offsetof(struct ReportConfigEUTRA__triggerType__event__eventId, present),
	sizeof(((struct ReportConfigEUTRA__triggerType__event__eventId *)0)->present),
	asn_MAP_eventId_tag2el_4,
	5,	/* Count of tags in the map */
	0,
	5	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_eventId_4 = {
	"eventId",
	"eventId",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_eventId_constr_4,
	asn_MBR_eventId_4,
	5,	/* Elements count */
	&asn_SPC_eventId_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_event_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event, eventId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_eventId_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"eventId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event, hysteresis),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Hysteresis,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"hysteresis"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__event, timeToTrigger),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeToTrigger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeToTrigger"
		},
};
static ber_tlv_tag_t asn_DEF_event_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_event_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eventId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* hysteresis */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeToTrigger */
};
static asn_SEQUENCE_specifics_t asn_SPC_event_specs_3 = {
	sizeof(struct ReportConfigEUTRA__triggerType__event),
	offsetof(struct ReportConfigEUTRA__triggerType__event, _asn_ctx),
	asn_MAP_event_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_event_3 = {
	"event",
	"event",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_event_tags_3,
	sizeof(asn_DEF_event_tags_3)
		/sizeof(asn_DEF_event_tags_3[0]) - 1, /* 1 */
	asn_DEF_event_tags_3,	/* Same as above */
	sizeof(asn_DEF_event_tags_3)
		/sizeof(asn_DEF_event_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_event_3,
	3,	/* Elements count */
	&asn_SPC_event_specs_3	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_purpose_value2enum_21[] = {
	{ 0,	20,	"reportStrongestCells" },
	{ 1,	9,	"reportCGI" }
};
static unsigned int asn_MAP_purpose_enum2value_21[] = {
	1,	/* reportCGI(1) */
	0	/* reportStrongestCells(0) */
};
static asn_INTEGER_specifics_t asn_SPC_purpose_specs_21 = {
	asn_MAP_purpose_value2enum_21,	/* "tag" => N; sorted by tag */
	asn_MAP_purpose_enum2value_21,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_purpose_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_purpose_21 = {
	"purpose",
	"purpose",
	purpose_21_free,
	purpose_21_print,
	purpose_21_constraint,
	purpose_21_decode_ber,
	purpose_21_encode_der,
	purpose_21_decode_xer,
	purpose_21_encode_xer,
	purpose_21_decode_uper,
	purpose_21_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_purpose_tags_21,
	sizeof(asn_DEF_purpose_tags_21)
		/sizeof(asn_DEF_purpose_tags_21[0]) - 1, /* 1 */
	asn_DEF_purpose_tags_21,	/* Same as above */
	sizeof(asn_DEF_purpose_tags_21)
		/sizeof(asn_DEF_purpose_tags_21[0]), /* 2 */
	&asn_PER_type_purpose_constr_21,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_purpose_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_periodical_20[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType__periodical, purpose),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_purpose_21,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"purpose"
		},
};
static ber_tlv_tag_t asn_DEF_periodical_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_periodical_tag2el_20[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* purpose */
};
static asn_SEQUENCE_specifics_t asn_SPC_periodical_specs_20 = {
	sizeof(struct ReportConfigEUTRA__triggerType__periodical),
	offsetof(struct ReportConfigEUTRA__triggerType__periodical, _asn_ctx),
	asn_MAP_periodical_tag2el_20,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_periodical_20 = {
	"periodical",
	"periodical",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_periodical_tags_20,
	sizeof(asn_DEF_periodical_tags_20)
		/sizeof(asn_DEF_periodical_tags_20[0]) - 1, /* 1 */
	asn_DEF_periodical_tags_20,	/* Same as above */
	sizeof(asn_DEF_periodical_tags_20)
		/sizeof(asn_DEF_periodical_tags_20[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_periodical_20,
	1,	/* Elements count */
	&asn_SPC_periodical_specs_20	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_triggerType_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType, choice.event),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_event_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"event"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA__triggerType, choice.periodical),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_periodical_20,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"periodical"
		},
};
static asn_TYPE_tag2member_t asn_MAP_triggerType_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* event */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* periodical */
};
static asn_CHOICE_specifics_t asn_SPC_triggerType_specs_2 = {
	sizeof(struct ReportConfigEUTRA__triggerType),
	offsetof(struct ReportConfigEUTRA__triggerType, _asn_ctx),
	offsetof(struct ReportConfigEUTRA__triggerType, present),
	sizeof(((struct ReportConfigEUTRA__triggerType *)0)->present),
	asn_MAP_triggerType_tag2el_2,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_triggerType_2 = {
	"triggerType",
	"triggerType",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_triggerType_constr_2,
	asn_MBR_triggerType_2,
	2,	/* Elements count */
	&asn_SPC_triggerType_specs_2	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_triggerQuantity_value2enum_24[] = {
	{ 0,	4,	"rsrp" },
	{ 1,	4,	"rsrq" }
};
static unsigned int asn_MAP_triggerQuantity_enum2value_24[] = {
	0,	/* rsrp(0) */
	1	/* rsrq(1) */
};
static asn_INTEGER_specifics_t asn_SPC_triggerQuantity_specs_24 = {
	asn_MAP_triggerQuantity_value2enum_24,	/* "tag" => N; sorted by tag */
	asn_MAP_triggerQuantity_enum2value_24,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_triggerQuantity_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_triggerQuantity_24 = {
	"triggerQuantity",
	"triggerQuantity",
	triggerQuantity_24_free,
	triggerQuantity_24_print,
	triggerQuantity_24_constraint,
	triggerQuantity_24_decode_ber,
	triggerQuantity_24_encode_der,
	triggerQuantity_24_decode_xer,
	triggerQuantity_24_encode_xer,
	triggerQuantity_24_decode_uper,
	triggerQuantity_24_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_triggerQuantity_tags_24,
	sizeof(asn_DEF_triggerQuantity_tags_24)
		/sizeof(asn_DEF_triggerQuantity_tags_24[0]) - 1, /* 1 */
	asn_DEF_triggerQuantity_tags_24,	/* Same as above */
	sizeof(asn_DEF_triggerQuantity_tags_24)
		/sizeof(asn_DEF_triggerQuantity_tags_24[0]), /* 2 */
	&asn_PER_type_triggerQuantity_constr_24,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_triggerQuantity_specs_24	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_reportQuantity_value2enum_27[] = {
	{ 0,	21,	"sameAsTriggerQuantity" },
	{ 1,	4,	"both" }
};
static unsigned int asn_MAP_reportQuantity_enum2value_27[] = {
	1,	/* both(1) */
	0	/* sameAsTriggerQuantity(0) */
};
static asn_INTEGER_specifics_t asn_SPC_reportQuantity_specs_27 = {
	asn_MAP_reportQuantity_value2enum_27,	/* "tag" => N; sorted by tag */
	asn_MAP_reportQuantity_enum2value_27,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_reportQuantity_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportQuantity_27 = {
	"reportQuantity",
	"reportQuantity",
	reportQuantity_27_free,
	reportQuantity_27_print,
	reportQuantity_27_constraint,
	reportQuantity_27_decode_ber,
	reportQuantity_27_encode_der,
	reportQuantity_27_decode_xer,
	reportQuantity_27_encode_xer,
	reportQuantity_27_decode_uper,
	reportQuantity_27_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_reportQuantity_tags_27,
	sizeof(asn_DEF_reportQuantity_tags_27)
		/sizeof(asn_DEF_reportQuantity_tags_27[0]) - 1, /* 1 */
	asn_DEF_reportQuantity_tags_27,	/* Same as above */
	sizeof(asn_DEF_reportQuantity_tags_27)
		/sizeof(asn_DEF_reportQuantity_tags_27[0]), /* 2 */
	&asn_PER_type_reportQuantity_constr_27,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportQuantity_specs_27	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_reportAmount_value2enum_32[] = {
	{ 0,	2,	"r1" },
	{ 1,	2,	"r2" },
	{ 2,	2,	"r4" },
	{ 3,	2,	"r8" },
	{ 4,	3,	"r16" },
	{ 5,	3,	"r32" },
	{ 6,	3,	"r64" },
	{ 7,	8,	"infinity" }
};
static unsigned int asn_MAP_reportAmount_enum2value_32[] = {
	7,	/* infinity(7) */
	0,	/* r1(0) */
	4,	/* r16(4) */
	1,	/* r2(1) */
	5,	/* r32(5) */
	2,	/* r4(2) */
	6,	/* r64(6) */
	3	/* r8(3) */
};
static asn_INTEGER_specifics_t asn_SPC_reportAmount_specs_32 = {
	asn_MAP_reportAmount_value2enum_32,	/* "tag" => N; sorted by tag */
	asn_MAP_reportAmount_enum2value_32,	/* N => "tag"; sorted by N */
	8,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_reportAmount_tags_32[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_reportAmount_32 = {
	"reportAmount",
	"reportAmount",
	reportAmount_32_free,
	reportAmount_32_print,
	reportAmount_32_constraint,
	reportAmount_32_decode_ber,
	reportAmount_32_encode_der,
	reportAmount_32_decode_xer,
	reportAmount_32_encode_xer,
	reportAmount_32_decode_uper,
	reportAmount_32_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_reportAmount_tags_32,
	sizeof(asn_DEF_reportAmount_tags_32)
		/sizeof(asn_DEF_reportAmount_tags_32[0]) - 1, /* 1 */
	asn_DEF_reportAmount_tags_32,	/* Same as above */
	sizeof(asn_DEF_reportAmount_tags_32)
		/sizeof(asn_DEF_reportAmount_tags_32[0]), /* 2 */
	&asn_PER_type_reportAmount_constr_32,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_reportAmount_specs_32	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ReportConfigEUTRA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA, triggerType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_triggerType_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"triggerType"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA, triggerQuantity),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_triggerQuantity_24,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"triggerQuantity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA, reportQuantity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportQuantity_27,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportQuantity"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA, maxReportCells),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_maxReportCells_constraint_1,
		&asn_PER_memb_maxReportCells_constr_30,
		0,
		"maxReportCells"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA, reportInterval),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReportInterval,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportInterval"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ReportConfigEUTRA, reportAmount),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_reportAmount_32,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reportAmount"
		},
};
static ber_tlv_tag_t asn_DEF_ReportConfigEUTRA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_ReportConfigEUTRA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* triggerType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* triggerQuantity */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* reportQuantity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* maxReportCells */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* reportInterval */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* reportAmount */
};
static asn_SEQUENCE_specifics_t asn_SPC_ReportConfigEUTRA_specs_1 = {
	sizeof(struct ReportConfigEUTRA),
	offsetof(struct ReportConfigEUTRA, _asn_ctx),
	asn_MAP_ReportConfigEUTRA_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* Start extensions */
	7	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ReportConfigEUTRA = {
	"ReportConfigEUTRA",
	"ReportConfigEUTRA",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ReportConfigEUTRA_tags_1,
	sizeof(asn_DEF_ReportConfigEUTRA_tags_1)
		/sizeof(asn_DEF_ReportConfigEUTRA_tags_1[0]), /* 1 */
	asn_DEF_ReportConfigEUTRA_tags_1,	/* Same as above */
	sizeof(asn_DEF_ReportConfigEUTRA_tags_1)
		/sizeof(asn_DEF_ReportConfigEUTRA_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ReportConfigEUTRA_1,
	6,	/* Elements count */
	&asn_SPC_ReportConfigEUTRA_specs_1	/* Additional specs */
};

