/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#include "RLF-Report-r9.h"

static int
connectionFailureType_r10_19_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
connectionFailureType_r10_19_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
connectionFailureType_r10_19_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
connectionFailureType_r10_19_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
connectionFailureType_r10_19_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
connectionFailureType_r10_19_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
connectionFailureType_r10_19_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
connectionFailureType_r10_19_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
connectionFailureType_r10_19_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
connectionFailureType_r10_19_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	connectionFailureType_r10_19_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
rlf_Cause_r11_27_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
rlf_Cause_r11_27_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

static void
rlf_Cause_r11_27_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
rlf_Cause_r11_27_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
rlf_Cause_r11_27_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
rlf_Cause_r11_27_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
rlf_Cause_r11_27_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
rlf_Cause_r11_27_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_dec_rval_t
rlf_Cause_r11_27_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

static asn_enc_rval_t
rlf_Cause_r11_27_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	rlf_Cause_r11_27_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static int
memb_timeConnFailure_r10_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_failedPCellId_r10_constr_12 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_connectionFailureType_r10_constr_19 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_rlf_Cause_r11_constr_27 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  3 }	/* (0..3) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_physCellId_r11_constr_35 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_physCellId_r11_constr_41 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_timeConnFailure_r10_constr_18 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 10,  10,  0,  1023 }	/* (0..1023) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_measResultLastServCell_r9_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__measResultLastServCell_r9, rsrpResult_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rsrpResult-r9"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__measResultLastServCell_r9, rsrqResult_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rsrqResult-r9"
		},
};
static int asn_MAP_measResultLastServCell_r9_oms_2[] = { 1 };
static ber_tlv_tag_t asn_DEF_measResultLastServCell_r9_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_measResultLastServCell_r9_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rsrqResult-r9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResultLastServCell_r9_specs_2 = {
	sizeof(struct RLF_Report_r9__measResultLastServCell_r9),
	offsetof(struct RLF_Report_r9__measResultLastServCell_r9, _asn_ctx),
	asn_MAP_measResultLastServCell_r9_tag2el_2,
	2,	/* Count of tags in the map */
	asn_MAP_measResultLastServCell_r9_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultLastServCell_r9_2 = {
	"measResultLastServCell-r9",
	"measResultLastServCell-r9",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_measResultLastServCell_r9_tags_2,
	sizeof(asn_DEF_measResultLastServCell_r9_tags_2)
		/sizeof(asn_DEF_measResultLastServCell_r9_tags_2[0]) - 1, /* 1 */
	asn_DEF_measResultLastServCell_r9_tags_2,	/* Same as above */
	sizeof(asn_DEF_measResultLastServCell_r9_tags_2)
		/sizeof(asn_DEF_measResultLastServCell_r9_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_measResultLastServCell_r9_2,
	2,	/* Elements count */
	&asn_SPC_measResultLastServCell_r9_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResultNeighCells_r9_5[] = {
	{ ATF_POINTER, 4, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultListEUTRA_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultList2EUTRA_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResultListEUTRA-r9"
		},
	{ ATF_POINTER, 3, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultListUTRA_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultList2UTRA_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResultListUTRA-r9"
		},
	{ ATF_POINTER, 2, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultListGERAN_r9),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultListGERAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResultListGERAN-r9"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__measResultNeighCells_r9, measResultsCDMA2000_r9),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultList2CDMA2000_r9,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResultsCDMA2000-r9"
		},
};
static int asn_MAP_measResultNeighCells_r9_oms_5[] = { 0, 1, 2, 3 };
static ber_tlv_tag_t asn_DEF_measResultNeighCells_r9_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_measResultNeighCells_r9_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultListEUTRA-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultListUTRA-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* measResultListGERAN-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* measResultsCDMA2000-r9 */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResultNeighCells_r9_specs_5 = {
	sizeof(struct RLF_Report_r9__measResultNeighCells_r9),
	offsetof(struct RLF_Report_r9__measResultNeighCells_r9, _asn_ctx),
	asn_MAP_measResultNeighCells_r9_tag2el_5,
	4,	/* Count of tags in the map */
	asn_MAP_measResultNeighCells_r9_oms_5,	/* Optional members */
	4, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResultNeighCells_r9_5 = {
	"measResultNeighCells-r9",
	"measResultNeighCells-r9",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_measResultNeighCells_r9_tags_5,
	sizeof(asn_DEF_measResultNeighCells_r9_tags_5)
		/sizeof(asn_DEF_measResultNeighCells_r9_tags_5[0]) - 1, /* 1 */
	asn_DEF_measResultNeighCells_r9_tags_5,	/* Same as above */
	sizeof(asn_DEF_measResultNeighCells_r9_tags_5)
		/sizeof(asn_DEF_measResultNeighCells_r9_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_measResultNeighCells_r9_5,
	4,	/* Elements count */
	&asn_SPC_measResultNeighCells_r9_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_pci_arfcn_r10_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__failedPCellId_r10__pci_arfcn_r10, physCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"physCellId-r10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__failedPCellId_r10__pci_arfcn_r10, carrierFreq_r10),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierFreq-r10"
		},
};
static ber_tlv_tag_t asn_DEF_pci_arfcn_r10_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_pci_arfcn_r10_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* carrierFreq-r10 */
};
static asn_SEQUENCE_specifics_t asn_SPC_pci_arfcn_r10_specs_14 = {
	sizeof(struct RLF_Report_r9__failedPCellId_r10__pci_arfcn_r10),
	offsetof(struct RLF_Report_r9__failedPCellId_r10__pci_arfcn_r10, _asn_ctx),
	asn_MAP_pci_arfcn_r10_tag2el_14,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pci_arfcn_r10_14 = {
	"pci-arfcn-r10",
	"pci-arfcn-r10",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_pci_arfcn_r10_tags_14,
	sizeof(asn_DEF_pci_arfcn_r10_tags_14)
		/sizeof(asn_DEF_pci_arfcn_r10_tags_14[0]) - 1, /* 1 */
	asn_DEF_pci_arfcn_r10_tags_14,	/* Same as above */
	sizeof(asn_DEF_pci_arfcn_r10_tags_14)
		/sizeof(asn_DEF_pci_arfcn_r10_tags_14[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_pci_arfcn_r10_14,
	2,	/* Elements count */
	&asn_SPC_pci_arfcn_r10_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_failedPCellId_r10_12[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__failedPCellId_r10, choice.cellGlobalId_r10),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellGlobalId-r10"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__failedPCellId_r10, choice.pci_arfcn_r10),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_pci_arfcn_r10_14,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"pci-arfcn-r10"
		},
};
static asn_TYPE_tag2member_t asn_MAP_failedPCellId_r10_tag2el_12[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGlobalId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* pci-arfcn-r10 */
};
static asn_CHOICE_specifics_t asn_SPC_failedPCellId_r10_specs_12 = {
	sizeof(struct RLF_Report_r9__failedPCellId_r10),
	offsetof(struct RLF_Report_r9__failedPCellId_r10, _asn_ctx),
	offsetof(struct RLF_Report_r9__failedPCellId_r10, present),
	sizeof(((struct RLF_Report_r9__failedPCellId_r10 *)0)->present),
	asn_MAP_failedPCellId_r10_tag2el_12,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_failedPCellId_r10_12 = {
	"failedPCellId-r10",
	"failedPCellId-r10",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_failedPCellId_r10_constr_12,
	asn_MBR_failedPCellId_r10_12,
	2,	/* Elements count */
	&asn_SPC_failedPCellId_r10_specs_12	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_connectionFailureType_r10_value2enum_19[] = {
	{ 0,	3,	"rlf" },
	{ 1,	3,	"hof" }
};
static unsigned int asn_MAP_connectionFailureType_r10_enum2value_19[] = {
	1,	/* hof(1) */
	0	/* rlf(0) */
};
static asn_INTEGER_specifics_t asn_SPC_connectionFailureType_r10_specs_19 = {
	asn_MAP_connectionFailureType_r10_value2enum_19,	/* "tag" => N; sorted by tag */
	asn_MAP_connectionFailureType_r10_enum2value_19,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_connectionFailureType_r10_tags_19[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connectionFailureType_r10_19 = {
	"connectionFailureType-r10",
	"connectionFailureType-r10",
	connectionFailureType_r10_19_free,
	connectionFailureType_r10_19_print,
	connectionFailureType_r10_19_constraint,
	connectionFailureType_r10_19_decode_ber,
	connectionFailureType_r10_19_encode_der,
	connectionFailureType_r10_19_decode_xer,
	connectionFailureType_r10_19_encode_xer,
	connectionFailureType_r10_19_decode_uper,
	connectionFailureType_r10_19_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_connectionFailureType_r10_tags_19,
	sizeof(asn_DEF_connectionFailureType_r10_tags_19)
		/sizeof(asn_DEF_connectionFailureType_r10_tags_19[0]) - 1, /* 1 */
	asn_DEF_connectionFailureType_r10_tags_19,	/* Same as above */
	sizeof(asn_DEF_connectionFailureType_r10_tags_19)
		/sizeof(asn_DEF_connectionFailureType_r10_tags_19[0]), /* 2 */
	&asn_PER_type_connectionFailureType_r10_constr_19,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_connectionFailureType_r10_specs_19	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_failedPCellId_v1090_23[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__failedPCellId_v1090, carrierFreq_v1090),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueEUTRA_v9e0,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierFreq-v1090"
		},
};
static ber_tlv_tag_t asn_DEF_failedPCellId_v1090_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_failedPCellId_v1090_tag2el_23[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* carrierFreq-v1090 */
};
static asn_SEQUENCE_specifics_t asn_SPC_failedPCellId_v1090_specs_23 = {
	sizeof(struct RLF_Report_r9__failedPCellId_v1090),
	offsetof(struct RLF_Report_r9__failedPCellId_v1090, _asn_ctx),
	asn_MAP_failedPCellId_v1090_tag2el_23,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_failedPCellId_v1090_23 = {
	"failedPCellId-v1090",
	"failedPCellId-v1090",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_failedPCellId_v1090_tags_23,
	sizeof(asn_DEF_failedPCellId_v1090_tags_23)
		/sizeof(asn_DEF_failedPCellId_v1090_tags_23[0]) - 1, /* 1 */
	asn_DEF_failedPCellId_v1090_tags_23,	/* Same as above */
	sizeof(asn_DEF_failedPCellId_v1090_tags_23)
		/sizeof(asn_DEF_failedPCellId_v1090_tags_23[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_failedPCellId_v1090_23,
	1,	/* Elements count */
	&asn_SPC_failedPCellId_v1090_specs_23	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_rlf_Cause_r11_value2enum_27[] = {
	{ 0,	11,	"t310-Expiry" },
	{ 1,	19,	"randomAccessProblem" },
	{ 2,	14,	"rlc-MaxNumRetx" },
	{ 3,	6,	"spare1" }
};
static unsigned int asn_MAP_rlf_Cause_r11_enum2value_27[] = {
	1,	/* randomAccessProblem(1) */
	2,	/* rlc-MaxNumRetx(2) */
	3,	/* spare1(3) */
	0	/* t310-Expiry(0) */
};
static asn_INTEGER_specifics_t asn_SPC_rlf_Cause_r11_specs_27 = {
	asn_MAP_rlf_Cause_r11_value2enum_27,	/* "tag" => N; sorted by tag */
	asn_MAP_rlf_Cause_r11_enum2value_27,	/* N => "tag"; sorted by N */
	4,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_rlf_Cause_r11_tags_27[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rlf_Cause_r11_27 = {
	"rlf-Cause-r11",
	"rlf-Cause-r11",
	rlf_Cause_r11_27_free,
	rlf_Cause_r11_27_print,
	rlf_Cause_r11_27_constraint,
	rlf_Cause_r11_27_decode_ber,
	rlf_Cause_r11_27_encode_der,
	rlf_Cause_r11_27_decode_xer,
	rlf_Cause_r11_27_encode_xer,
	rlf_Cause_r11_27_decode_uper,
	rlf_Cause_r11_27_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_rlf_Cause_r11_tags_27,
	sizeof(asn_DEF_rlf_Cause_r11_tags_27)
		/sizeof(asn_DEF_rlf_Cause_r11_tags_27[0]) - 1, /* 1 */
	asn_DEF_rlf_Cause_r11_tags_27,	/* Same as above */
	sizeof(asn_DEF_rlf_Cause_r11_tags_27)
		/sizeof(asn_DEF_rlf_Cause_r11_tags_27[0]), /* 2 */
	&asn_PER_type_rlf_Cause_r11_constr_27,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rlf_Cause_r11_specs_27	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_basicFields_r11_25[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__basicFields_r11, c_RNTI_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_C_RNTI,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"c-RNTI-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__basicFields_r11, rlf_Cause_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rlf_Cause_r11_27,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"rlf-Cause-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__basicFields_r11, timeSinceFailure_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeSinceFailure_r11,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"timeSinceFailure-r11"
		},
};
static ber_tlv_tag_t asn_DEF_basicFields_r11_tags_25[] = {
	(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_basicFields_r11_tag2el_25[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c-RNTI-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rlf-Cause-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* timeSinceFailure-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_basicFields_r11_specs_25 = {
	sizeof(struct RLF_Report_r9__basicFields_r11),
	offsetof(struct RLF_Report_r9__basicFields_r11, _asn_ctx),
	asn_MAP_basicFields_r11_tag2el_25,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_basicFields_r11_25 = {
	"basicFields-r11",
	"basicFields-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_basicFields_r11_tags_25,
	sizeof(asn_DEF_basicFields_r11_tags_25)
		/sizeof(asn_DEF_basicFields_r11_tags_25[0]) - 1, /* 1 */
	asn_DEF_basicFields_r11_tags_25,	/* Same as above */
	sizeof(asn_DEF_basicFields_r11_tags_25)
		/sizeof(asn_DEF_basicFields_r11_tags_25[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_basicFields_r11_25,
	3,	/* Elements count */
	&asn_SPC_basicFields_r11_specs_25	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_physCellId_r11_35[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11__physCellId_r11, choice.fdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_FDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fdd-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11__physCellId_r11, choice.tdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_TDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tdd-r11"
		},
};
static asn_TYPE_tag2member_t asn_MAP_physCellId_r11_tag2el_35[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-r11 */
};
static asn_CHOICE_specifics_t asn_SPC_physCellId_r11_specs_35 = {
	sizeof(struct RLF_Report_r9__previousUTRA_CellId_r11__physCellId_r11),
	offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11__physCellId_r11, _asn_ctx),
	offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11__physCellId_r11, present),
	sizeof(((struct RLF_Report_r9__previousUTRA_CellId_r11__physCellId_r11 *)0)->present),
	asn_MAP_physCellId_r11_tag2el_35,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_physCellId_r11_35 = {
	"physCellId-r11",
	"physCellId-r11",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_physCellId_r11_constr_35,
	asn_MBR_physCellId_r11_35,
	2,	/* Elements count */
	&asn_SPC_physCellId_r11_specs_35	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_previousUTRA_CellId_r11_33[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11, carrierFreq_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierFreq-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11, physCellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_physCellId_r11_35,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"physCellId-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11, cellGlobalId_r11),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"cellGlobalId-r11"
		},
};
static int asn_MAP_previousUTRA_CellId_r11_oms_33[] = { 2 };
static ber_tlv_tag_t asn_DEF_previousUTRA_CellId_r11_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_previousUTRA_CellId_r11_tag2el_33[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierFreq-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* physCellId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* cellGlobalId-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_previousUTRA_CellId_r11_specs_33 = {
	sizeof(struct RLF_Report_r9__previousUTRA_CellId_r11),
	offsetof(struct RLF_Report_r9__previousUTRA_CellId_r11, _asn_ctx),
	asn_MAP_previousUTRA_CellId_r11_tag2el_33,
	3,	/* Count of tags in the map */
	asn_MAP_previousUTRA_CellId_r11_oms_33,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_previousUTRA_CellId_r11_33 = {
	"previousUTRA-CellId-r11",
	"previousUTRA-CellId-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_previousUTRA_CellId_r11_tags_33,
	sizeof(asn_DEF_previousUTRA_CellId_r11_tags_33)
		/sizeof(asn_DEF_previousUTRA_CellId_r11_tags_33[0]) - 1, /* 1 */
	asn_DEF_previousUTRA_CellId_r11_tags_33,	/* Same as above */
	sizeof(asn_DEF_previousUTRA_CellId_r11_tags_33)
		/sizeof(asn_DEF_previousUTRA_CellId_r11_tags_33[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_previousUTRA_CellId_r11_33,
	3,	/* Elements count */
	&asn_SPC_previousUTRA_CellId_r11_specs_33	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_physCellId_r11_41[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11__physCellId_r11, choice.fdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_FDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"fdd-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11__physCellId_r11, choice.tdd_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdUTRA_TDD,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"tdd-r11"
		},
};
static asn_TYPE_tag2member_t asn_MAP_physCellId_r11_tag2el_41[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* fdd-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tdd-r11 */
};
static asn_CHOICE_specifics_t asn_SPC_physCellId_r11_specs_41 = {
	sizeof(struct RLF_Report_r9__selectedUTRA_CellId_r11__physCellId_r11),
	offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11__physCellId_r11, _asn_ctx),
	offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11__physCellId_r11, present),
	sizeof(((struct RLF_Report_r9__selectedUTRA_CellId_r11__physCellId_r11 *)0)->present),
	asn_MAP_physCellId_r11_tag2el_41,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_physCellId_r11_41 = {
	"physCellId-r11",
	"physCellId-r11",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	CHOICE_decode_uper,
	CHOICE_encode_uper,
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	&asn_PER_type_physCellId_r11_constr_41,
	asn_MBR_physCellId_r11_41,
	2,	/* Elements count */
	&asn_SPC_physCellId_r11_specs_41	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_selectedUTRA_CellId_r11_39[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11, carrierFreq_r11),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"carrierFreq-r11"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11, physCellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_physCellId_r11_41,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"physCellId-r11"
		},
};
static ber_tlv_tag_t asn_DEF_selectedUTRA_CellId_r11_tags_39[] = {
	(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_selectedUTRA_CellId_r11_tag2el_39[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierFreq-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* physCellId-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_selectedUTRA_CellId_r11_specs_39 = {
	sizeof(struct RLF_Report_r9__selectedUTRA_CellId_r11),
	offsetof(struct RLF_Report_r9__selectedUTRA_CellId_r11, _asn_ctx),
	asn_MAP_selectedUTRA_CellId_r11_tag2el_39,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_selectedUTRA_CellId_r11_39 = {
	"selectedUTRA-CellId-r11",
	"selectedUTRA-CellId-r11",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_selectedUTRA_CellId_r11_tags_39,
	sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_39)
		/sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_39[0]) - 1, /* 1 */
	asn_DEF_selectedUTRA_CellId_r11_tags_39,	/* Same as above */
	sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_39)
		/sizeof(asn_DEF_selectedUTRA_CellId_r11_tags_39[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_selectedUTRA_CellId_r11_39,
	2,	/* Elements count */
	&asn_SPC_selectedUTRA_CellId_r11_specs_39	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_RLF_Report_r9_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RLF_Report_r9, measResultLastServCell_r9),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_measResultLastServCell_r9_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResultLastServCell-r9"
		},
	{ ATF_POINTER, 11, offsetof(struct RLF_Report_r9, measResultNeighCells_r9),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_measResultNeighCells_r9_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"measResultNeighCells-r9"
		},
	{ ATF_POINTER, 10, offsetof(struct RLF_Report_r9, locationInfo_r10),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationInfo_r10,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"locationInfo-r10"
		},
	{ ATF_POINTER, 9, offsetof(struct RLF_Report_r9, failedPCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_failedPCellId_r10_12,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"failedPCellId-r10"
		},
	{ ATF_POINTER, 8, offsetof(struct RLF_Report_r9, reestablishmentCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"reestablishmentCellId-r10"
		},
	{ ATF_POINTER, 7, offsetof(struct RLF_Report_r9, timeConnFailure_r10),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		memb_timeConnFailure_r10_constraint_1,
		&asn_PER_memb_timeConnFailure_r10_constr_18,
		0,
		"timeConnFailure-r10"
		},
	{ ATF_POINTER, 6, offsetof(struct RLF_Report_r9, connectionFailureType_r10),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_connectionFailureType_r10_19,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"connectionFailureType-r10"
		},
	{ ATF_POINTER, 5, offsetof(struct RLF_Report_r9, previousPCellId_r10),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"previousPCellId-r10"
		},
	{ ATF_POINTER, 4, offsetof(struct RLF_Report_r9, failedPCellId_v1090),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		0,
		&asn_DEF_failedPCellId_v1090_23,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"failedPCellId-v1090"
		},
	{ ATF_POINTER, 3, offsetof(struct RLF_Report_r9, basicFields_r11),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		0,
		&asn_DEF_basicFields_r11_25,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"basicFields-r11"
		},
	{ ATF_POINTER, 2, offsetof(struct RLF_Report_r9, previousUTRA_CellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		0,
		&asn_DEF_previousUTRA_CellId_r11_33,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"previousUTRA-CellId-r11"
		},
	{ ATF_POINTER, 1, offsetof(struct RLF_Report_r9, selectedUTRA_CellId_r11),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		0,
		&asn_DEF_selectedUTRA_CellId_r11_39,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"selectedUTRA-CellId-r11"
		},
};
static int asn_MAP_RLF_Report_r9_oms_1[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 };
static ber_tlv_tag_t asn_DEF_RLF_Report_r9_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_RLF_Report_r9_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* measResultLastServCell-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultNeighCells-r9 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* locationInfo-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* failedPCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* reestablishmentCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* timeConnFailure-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* connectionFailureType-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* previousPCellId-r10 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* failedPCellId-v1090 */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* basicFields-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* previousUTRA-CellId-r11 */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 } /* selectedUTRA-CellId-r11 */
};
static asn_SEQUENCE_specifics_t asn_SPC_RLF_Report_r9_specs_1 = {
	sizeof(struct RLF_Report_r9),
	offsetof(struct RLF_Report_r9, _asn_ctx),
	asn_MAP_RLF_Report_r9_tag2el_1,
	12,	/* Count of tags in the map */
	asn_MAP_RLF_Report_r9_oms_1,	/* Optional members */
	1, 10,	/* Root/Additions */
	1,	/* Start extensions */
	13	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_RLF_Report_r9 = {
	"RLF-Report-r9",
	"RLF-Report-r9",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_RLF_Report_r9_tags_1,
	sizeof(asn_DEF_RLF_Report_r9_tags_1)
		/sizeof(asn_DEF_RLF_Report_r9_tags_1[0]), /* 1 */
	asn_DEF_RLF_Report_r9_tags_1,	/* Same as above */
	sizeof(asn_DEF_RLF_Report_r9_tags_1)
		/sizeof(asn_DEF_RLF_Report_r9_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_RLF_Report_r9_1,
	12,	/* Elements count */
	&asn_SPC_RLF_Report_r9_specs_1	/* Additional specs */
};

