/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_RRCConnectionReestablishmentComplete_v1130_IEs_H_
#define	_RRCConnectionReestablishmentComplete_v1130_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRCConnectionReestablishmentComplete_v1130_IEs__connEstFailInfoAvailable_r11 {
	RRCConnectionReestablishmentComplete_v1130_IEs__connEstFailInfoAvailable_r11_true	= 0
} e_RRCConnectionReestablishmentComplete_v1130_IEs__connEstFailInfoAvailable_r11;

/* RRCConnectionReestablishmentComplete-v1130-IEs */
typedef struct RRCConnectionReestablishmentComplete_v1130_IEs {
	long	*connEstFailInfoAvailable_r11	/* OPTIONAL */;
	struct RRCConnectionReestablishmentComplete_v1130_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReestablishmentComplete_v1130_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_connEstFailInfoAvailable_r11_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReestablishmentComplete_v1130_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionReestablishmentComplete_v1130_IEs_H_ */
#include <asn_internal.h>
