/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_SRS_AntennaPort_H_
#define	_SRS_AntennaPort_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SRS_AntennaPort {
	SRS_AntennaPort_an1	= 0,
	SRS_AntennaPort_an2	= 1,
	SRS_AntennaPort_an4	= 2,
	SRS_AntennaPort_spare1	= 3
} e_SRS_AntennaPort;

/* SRS-AntennaPort */
typedef long	 SRS_AntennaPort_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRS_AntennaPort;
asn_struct_free_f SRS_AntennaPort_free;
asn_struct_print_f SRS_AntennaPort_print;
asn_constr_check_f SRS_AntennaPort_constraint;
ber_type_decoder_f SRS_AntennaPort_decode_ber;
der_type_encoder_f SRS_AntennaPort_encode_der;
xer_type_decoder_f SRS_AntennaPort_decode_xer;
xer_type_encoder_f SRS_AntennaPort_encode_xer;
per_type_decoder_f SRS_AntennaPort_decode_uper;
per_type_encoder_f SRS_AntennaPort_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SRS_AntennaPort_H_ */
#include <asn_internal.h>
