/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-850.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_ULInformationTransfer_r8_IEs_H_
#define	_ULInformationTransfer_r8_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DedicatedInfoNAS.h"
#include "DedicatedInfoCDMA2000.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULInformationTransfer_r8_IEs__dedicatedInformationType_PR {
	ULInformationTransfer_r8_IEs__dedicatedInformationType_PR_NOTHING,	/* No components present */
	ULInformationTransfer_r8_IEs__dedicatedInformationType_PR_dedicatedInfoNAS,
	ULInformationTransfer_r8_IEs__dedicatedInformationType_PR_dedicatedInfoCDMA2000_1XRTT,
	ULInformationTransfer_r8_IEs__dedicatedInformationType_PR_dedicatedInfoCDMA2000_HRPD
} ULInformationTransfer_r8_IEs__dedicatedInformationType_PR;

/* ULInformationTransfer-r8-IEs */
typedef struct ULInformationTransfer_r8_IEs {
	struct ULInformationTransfer_r8_IEs__dedicatedInformationType {
		ULInformationTransfer_r8_IEs__dedicatedInformationType_PR present;
		union ULInformationTransfer_r8_IEs__dedicatedInformationType_u {
			DedicatedInfoNAS_t	 dedicatedInfoNAS;
			DedicatedInfoCDMA2000_t	 dedicatedInfoCDMA2000_1XRTT;
			DedicatedInfoCDMA2000_t	 dedicatedInfoCDMA2000_HRPD;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dedicatedInformationType;
	struct ULInformationTransfer_r8_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULInformationTransfer_r8_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ULInformationTransfer_r8_IEs;

#ifdef __cplusplus
}
#endif

#endif	/* _ULInformationTransfer_r8_IEs_H_ */
#include <asn_internal.h>
