/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "36331-c10.asn"
 * 	`asn1c -S /usr/local/share/asn1c -fcompound-names -fskeletons-copy -gen-PER`
 */

#ifndef	_UplinkPowerControlCommonSCell_v1130_H_
#define	_UplinkPowerControlCommonSCell_v1130_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UplinkPowerControlCommonSCell-v1130 */
typedef struct UplinkPowerControlCommonSCell_v1130 {
	long	 deltaPreambleMsg3_r11;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkPowerControlCommonSCell_v1130_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UplinkPowerControlCommonSCell_v1130;

#ifdef __cplusplus
}
#endif

#endif	/* _UplinkPowerControlCommonSCell_v1130_H_ */
#include <asn_internal.h>
